name: Microservices CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  python-checks:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - user-service
          - order-service
          - api-gateway
          - notification-service

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          cd ${{ matrix.service }}
          pip install -r requirements.txt

      - name: Python Syntax Check
        run: |
          cd ${{ matrix.service }}
          python -m py_compile *.py

      - name: Run Flake8
        run: |
          cd ${{ matrix.service }}
          flake8 . || true

  frontend-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  docker-build:

    needs:
      - python-checks
      - frontend-build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push User Service
        uses: docker/build-push-action@v6
        with:
          context: ./user-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      - name: Build and Push Order Service
        uses: docker/build-push-action@v6
        with:
          context: ./order-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/order-service:latest

      - name: Build and Push API Gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      - name: Build and Push Notification Service
        uses: docker/build-push-action@v6
        with:
          context: ./notification-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/notification-service:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
